name: Art work

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  List_Directory:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}  # ✅ evaluat înainte de shell
        run: |
          echo "$GITHUB_CONTEXT"